name: reporter

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: '00,15,30,45 * * * *'

jobs:
  granizo:
    name: granizo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: requirements
      run: pip install -r requirements.txt
    - name: python
      run: python main.py
      env:
        RADAR_URL: ${{ secrets.RADAR_URL }}
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
